"""init schema

Revision ID: 3d50bdd9ecd2
Revises: 
Create Date: 2026-03-25 01:21:59.715010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d50bdd9ecd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('new_transactions', sa.Integer(), nullable=False),
    sa.Column('duplicate_transactions', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_status', sa.String(length=30), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_transactions_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_booking_date'), 'transactions', ['booking_date'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_direction'), 'transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_transactions_duplicate_status'), 'transactions', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_import_job_id'), 'transactions', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_transactions_review_status'), 'transactions', ['review_status'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_transaction_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_tags_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_tags')),
    sa.UniqueConstraint('transaction_id', 'tag_id', name=op.f('uq_transaction_tags_transaction_id'))
    )
    op.create_index(op.f('ix_transaction_tags_tag_id'), 'transaction_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_transaction_tags_transaction_id'), 'transaction_tags', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_tags_transaction_id'), table_name='transaction_tags')
    op.drop_index(op.f('ix_transaction_tags_tag_id'), table_name='transaction_tags')
    op.drop_table('transaction_tags')
    op.drop_index(op.f('ix_transactions_review_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_job_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_duplicate_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_direction'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_table('categories')
    # ### end Alembic commands ###
